### PR TITLE
Modernizing the change dictionary to use the new string enum NSKeyValueChangeKey

### PR DESCRIPTION
**Pull request by mohamede1945**
This way it would help Swift bridging to use an enum for the change dictionary.

### CODE REVIEW

**Comment by nlutsenko** [comment]
This is a great modernization. Thank you!
Will merge as soon as the CI passes.

**Comment by mohamede1945** [comment]
Great! Thank you so much! Is it possible to publish a new Cocoapods version so that I can use it in my project?

**Comment by nlutsenko** [comment]
Sure, I don't see why not...
Also, be aware, this might actually fail CI, since it's still configured to use Xcode 7.3, but I am going to fix it in a little bit.

What this means is that you might need to rebase this pul request on top of the master.
Will update here as soon as I have something up.

**Comment by mohamede1945** [comment]
Sounds good to me! Thank you so much for the quick responses!

**Pull request merged**
