### PR TITLE
keyPath in FBKVONotificationBlock

### PR DESCRIPTION
**Pull request by tettoffensive**
Not sure if this is of interest to others, but in my projects, I've been using a modified version where the block also returns the `keyPath`. This becomes important when using the `keyPaths` method, so that you know which `keyPath` to use.

Of course, this is not backwards compatible with the current version on master. So, I'm open to suggestions if there's a way to make it work. But otherwise, I'll just stick with my custom version.

e.g.,
```
[self.KVOController observe:self.viewModel keyPaths:self.viewModel.keys options:NSKeyValueObservingOptionNew block:^(UIViewController *observer, ViewModel *viewModel, NSString *keyPath, NSDictionary *change) {
    // do if else logic here depending on which keypath it is
}];
```

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by nlutsenko** [comment]
This looks indeed very helpful!
There is a way to make it non-breaking - include the `keyPath` into the `change` dictionary and provide a public extern constant string to receive it back.

This way you don't have to break any public APIs and still build this as a new feature.

Proposed name for the key:
```
// FBKVOController.h
extern NSString *const FBKVONotificationKeyPathKey;

// FBKVOController.m
NSString *const FBKVONotificationKeyPathKey = @"FBKVONotificationKeyPathKey";
```

Let me know what do you think about this way of adding support for it (it's less optimal compared to yours, but is at least non-breaking).

**Comment by tettoffensive** [comment]
@nlutsenko That sounds like a good plan to prevent making a breaking change. It may be worth listing the keys in the doc as it's easy to forget what keys are available in `change`

**Comment by nlutsenko** [comment]
Sounds great! Looking forward to see this PR updated then (including the documentation for the block).

**Comment by tettoffensive** [comment]
See #114

**Pull request closed without merging**
