### PR TITLE
FBKVOControllerTests: Improve test coverage

### PR DESCRIPTION
**Pull request by modocache**
Add tests for methods:

- `-observe:keyPaths:options:block:`
- `-observe:keyPaths:options:action:`
- `-observe:keyPaths:options:context:`

### CODE REVIEW

**Comment by modocache** [comment]
This takes coverage from 55.59% to 63.04%: https://coveralls.io/builds/2369713

**Comment by modocache** [comment]
Adding a trivial test for `-debugDescription` brings coverage above 80%.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by grp** [comment]
Oh, why wasn't this merged?

**Pull request merged**
